/** Clean URLs aligned with the static site (site_urls.py). */
export const siteLinks = {
  home: "/",
  about: "/about",
  caseStudies: "/about/case-studies",
  waTax: "/washington-state-sales-tax-notice",
  insights: "/insights",
  contact: "/contact",
  privacy: "/privacy-policy",
  sitemap: "/sitemap",
  branding: "/branding",
  webDesign: "/web-design",
  socialMedia: "/social-media",
  googleAds: "/google-ads",
  seo: "/seo",
  pressReleases: "/press-releases",
  contentMarketing: "/content-marketing",
  servicesAnchor: "/#services",
  phone: "tel:5099019735",
  email: "mailto:info@yakimabranding.com",
  facebook: "https://www.facebook.com/yakimabranding",
  instagram: "https://www.instagram.com/yb.marketing_/",
  linkedin: "https://www.linkedin.com/company/18939370",
  location: (slug: string) => `/locations/${slug}`,
} as const;
